<h1>联系我们</h1>

<?php if($this->success) { ?>
<div class="alert alert-success"><?php echo $this->success; ?></div>
<?php } ?>
<form role="form" method="post" action="<?php echo $this->url('contact-us');?>">
  <div class="form-group">
    <label for="email">Email</label>
    <input type="email" name="email" class="form-control" id="email" placeholder="请输入email">
  </div>
  <div class="form-group">
    <label for="title">标题</label>
    <input type="text" name="title" class="form-control" id="title" placeholder="请输入标题">
  </div>
  <div class="form-group">
    <label for="content">内容</label>
    <textarea name="content" id="content" class="form-control" rows="3"></textarea>
  </div>

  <button type="submit" class="btn btn-default">提交</button>
  <a href="<?php echo $this->url('contact-us-list');?>">列表</a>
</form>